= UX-Konzept: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die Benutzeroberflächen des Systems {project-system-name} beschrieben. Dies können sein:

* Personas der wichtigsten Stakeholder
* Nutzerkontext
* Wireframes relevanter Benutzeroberflächen
* Zusammenhänge mittels Taskflow-Diagrammen
* Angaben über die Gestaltung der Benutzeroberfläche, z.B. Styling, Bedienbarkeit, ...

== Personas
// Fügen Sie hier als Tabelle oder Bild die Persons der wichtigsten Stakeholder ein
=== Laura Lehmann

[cols="2a,4a", options="header"]
|===

2+|*Demographie*

|image::../images/Persona(Laura_Lehmann).png[width=100%,alt="Persona Bild"]
|
* Alter: 27  
* Geschlecht: weiblich  
* Familienstand: ledig  
* Wohnsituation: 4er-WG  
* Beruf: Bürojob  

2+|*Technische Fähigkeiten / Technologie*

2+|
- Nutzt täglich Smartphone und Laptop Job und Organisation  
- Vertraut mit Technik, sowie dem Anlegen und Verwalten von Listen
- Hat bereits Erfahrung mit Haushaltsorganisation (mehrere Jahre WG-Erfahrung)  
- Nutzt auch andere Apps zur Organisation (z.B. Online-Banking)  
- Gute Internetverbindung  

2+|*Bedürfnisse / Ziele*

2+|
- Klare, faire Aufteilung von Kosten und Einkäufen  
- Einsehbare Historie: Wer hat was gekauft?  
- Nachvollziehbarkeit der Abrechnungen  
  (Warum muss ich diesen Betrag zahlen? / Was wurde bereits bezahlt?)  

2+|*Hindernisse / Frustrationen*

2+|
- Diskussionen darüber, wer wie viel bezahlt hat  
  → Wunsch nach klaren Abrechnungen mit Kostenübersicht  
- Diskussionen über Einkaufspflichten (wenn nicht klar is, wer wann einkaufen geht)  
- Zu komplizierte Benutzerführung, weshalb App nicht von allen WG-Bewohnern genutzt  
|===


== Nutzungskontext
// Beschreiben Sie die Arbeitsaufgaben, Arbeitsmittel, physische und soziale Umgebung, in der das Produkt genutzt wird. 
// Eventuell sind Angaben zu Fehlerquellen, Häufigkeiten von Ereignisse sowie Bearbeitungsdauern von Vorgängen relevant

//Hier sind einige Anregungen:

//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
. Anzahl der Personen, die an der Erfüllung der Aufgabe beteiligt sind. Ändert sich das?
. Wie lange dauert die Bearbeitung der Aufgabe? Wie viel Zeit wird für jeden Arbeitsschritt benötigt? Ändert sich das?
. Gibt es besondere Umgebungsbedingungen, z.B. mobil, offline, Außeneinsatz, Touchbedienung, Nutzung durch seh- oder hörbeeinträchtigte Personen?
. Welche Systemplattformen werden heute eingesetzt? Welche sind es ggf. zukünftig?
. Welche anderen Anwendungen sind im Einsatz? Muss ihre Anwendung mit diesen integriert werden?

Hier können zudem bei Bedarf Teile des Unternehmensmodells (Prozesse, Organigramme, IT-Landschaft, ...) eingefügt werden, um die beteiligten Aufgaben und Rollen zu skizzieren.

== Wireframes und Wireflow
// Fügen Sie Wireframes als Bilder oder als Link (z.B. zu einem Miroboard) ein
// Beziehen Sie ihre Wireframes auf konkrete User Stories oder Epics.