include::attributes.adoc[]

= {system-name}: Betriebs Dokumentation
{docdate}

== Systemvorraussetzungen

=== Hardwareanforderungen

* CPU: vergleichbar oder besser als Intel Xeon Gold 6132 (2) @ 2.593GHz
* Memory: 1000 MiB (für leere Datenbank)

=== Softwareanforderungen

==== mit Docker

* Docker
* Git

==== Manuell

* Betriebssystem: Ubuntu 24.04.2 LTS x86_64
* WebServer: Nginx 1.24.0
* Backend Runtime: Python 3.12.3
* Backend Framework: FastAPI 0.115.12
* ASGI Server: Uvicorn 0.34.3
* Datenbank: MySQL 8.0.44

== Systemeinrichtung

=== aktuelles System

* Anwendung: http://141.56.137.83/
* API: http://141.56.137.83:8000
* API-Dokumenation: http://141.56.137.83:8000/docs
* Voraussetzungen für die Nutzung:
** Netzwerkzugriff auf die Server-IP (VPN zur HTW Dresden)

=== Installation

==== mit Docker

Im Moment werden noch keine vorgefertigten Docker Images zur Verfügung gestellt.
Sie müssen eigenständig erstellt werden.
Dafür klonen Sie zuerst den "main" Branch des Remote Git Repository.

[source,bash]
----
git clone --branch main https://github.com/Pierro-e/HTWD-SE-shareshop_4B.git
----

Wechsele in das erstellte Verzeichnis, um die Quelldateien zu inspizieren.

[source,bash]
----
cd HTWD-SE-shareshop_4B
----

Anschließend müssen die Dockerfiles entsprechend des Anwendungszwecks
konfiguriert werden.
Die Anwendung umfasst 2 Dockerfiles und eine Compose Datei.
Sie erzeugen Images für die API und das UI.
Die Compose Datei erzeugt noch eine Datenbank und ist dafür gedacht,
alle 3 Anwendungskomponenten (UI, API und Datenbank) auf einem Host zu starten.
Es können aber auch alle Komponenten verteilt gehostet werden.

In der Datei "<git_root>/src/frontend/Dockerfile" muss die Base URL der API
definiert werden, da diese von Vite zur Buildzeit gebraucht wird.

[source,dockerfile]
----
# =========================================
# Stage 1: Vite
# =========================================

# ...

ENV VITE_API_BASE_URL=<api_base_url>

# ...
----

In der Compose Datei müssen noch die Eigenschaften der Datenbank definiert werden.
Zudem können noch Ports angepasst werden.

[source,yaml]
----
services:
  ui:
    build: ./frontend/
    ports:
      - "8080:8080"
    depends_on:
      - api
  api:
    build: ./backend/
    environment:
      DB_NAME: <name>
      DB_USER: <user>
      DB_PASSWORD: <password>
      DB_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: <name>
      MYSQL_USER: <user>
      MYSQL_PASSWORD: <password>
      MYSQL_ROOT_PASSWORD: <rootpassword>
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql_data:
----

Die komplette Anwendung kann dann erzeugt und gestartet werden.

[source,bash]
----
cd <git_root>/src/
docker compose build
docker compose up
----

Detalierte Informationen zur Verwaltung bietet die link:https://docs.docker.com/compose/[Docker Compose Dokumentation].

==== Manuell

===== Frontend (Vue.js)

. build erstellen mit:

[source,bash]
----
npm run build
----

. Build-Ausgabe ablegen unter: /var/www/shareshop/dist
. Auslieferung über Web Server (Nginx)

[source,bash]
----
sudo apt update
sudo apt install -y nginx
sudo nano /etc/nginx/sites-available/shareshop
sudo ln -sf /etc/nginx/sites-available/shareshop /etc/nginx/sites-enabled/shareshop
sudo nginx -t
sudo systemctl reload nginx
----

===== Web Server (Nginx)

. Frontend: "/"
. Weiterleitung an Backend: "8000"

==== API (FastAPI)

. Umgebungsvariablen
.. DB_HOST
.. DB_PASSWORD
.. DB_USER
.. DB_NAME
. Start über Uvicorn
. Betrieb als systemd-Service (fastapi.service)

==== Datenbank (MySQL)

. Datenbankname: share_shop
. DB erstellen mit:

[source,bash]
----
sudo apt install -y mysql-server
mysql -u root -p -e "CREATE DATABASE share_shop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
----

== Systembetreuung

=== FAQ für Benutzersupport

. Frontend lädt nicht
.. Nginx-Service prüfen
. API antwortet nicht
.. Status von fastapi.service prüfen
.. Backend-Logs einsehen
. Daten fehlen oder sind inkonsistent
.. MySQL-Service prüfen
.. Datenbank share_shop prüfen

=== Fehlerdiagnose (Logfile-Einträge)

* Backend-Logs: 'journalctl -u fastapi.service'
* Webserver-Logs: '/var/log/nginx/error.log'
* Datenbank-Logs: systemd (mysql.service)

=== Typische Fehler

* 502/504 -> Backend nicht erreichbar
* Datenbankfehler -> falsche Zugangsdaten oder DB nicht verfügbar

== Datensicherung und Wiederherstellung

=== Strategien

* Manuell
* Sicherung der Datenbank

=== Durchführung

* 'mysqldump -u root -p share_shop > backup.sql'

=== Wiederherstellung

* 'mysql -u root -p share_shop < share_shop'
* Quellcode liegt im GitHub-Repository
