= Projektplan: {project-name}
include::../_includes/default-attributes.inc.adoc[]

== Einführung

Dieses Dokument beschreibt das kollaborative Zusammenarbeiten innerhalb des Projektes.
Es erläutert die Projektorganisation, verwendete Arbeitsmethoden und den Einsatz von Tools zur effektiven Zusammenarbeit.

== Projektorganisation

=== Teammitglieder

[cols="1,1,1"]
|===
| Name | Kontaktdaten | SCRUM-Rolle

|*Maximilian Paul*
|s87085@htw-dresden.de
|Product Owner

|*Pierre Kißling*
|s86388@htw-dresden.de
|Scrum Master

|*Marlene Fritz*
|s87181@htw-dresden.de
|Development Team

|*Levin Heinrich*
|s87139@htw-dresden.de
|Development Team

|*Erik Wenke*
|s86221@htw-dresden.de
|Development Team
|===

=== Arbeitsumgebung

[cols="1,1"]
|===
| Funktionalität | Platform

| Remote Repository
|https://github.com/Pierro-e/HTWD-SE-shareshop_4B.git[*GitHub*]

| Projektmanagement
|https://github.com/users/Pierro-e/projects/3/views/14[*GitHub*]

| kollaboratives Arbeiten (z.B Brainstorming)
|https://miro.com/app/board/uXjVIEJUxFI=/[*Miro*]

| Online Meetings
| https://discord.gg/33mhPr53[*Discord*]

| Asynchrone Kommunikation
| https://chat.whatsapp.com/Iac09ptHXBkEWxya86PYra[*Whatsapp*]
|===

== Praktiken und Bewertung

* wöchentliches *Online Meeting* - Freitag 12:00 bis 13:30

=== Definition of Ready - Product Backlog Item

* PBI wurde von PO in PB aufgenommen (kein Label "vorschlag")
* Aktzeptanzkriterien sind ausgearbeitet

=== Definition of Done - Product Backlog Item

<<<<<<< HEAD
* Alle Sub-Issues (Tasks und Akzeptanzkriterien) sind abgeschlossen.
* Der Code wurde reviewed und abgenommen.
=======
* Alle Sub-Issues (Tasks oder Akzeptanzkriterien) sind abgeschlossen
* Arbeit ist ins Remote Repository aufgenommen
* PBI wurde im wöchentlichen Meeting besprochen
>>>>>>> developer

== Deployment

* aktuellen Zustand im wöchentlichen Meeting besprechen
* bei Bedarf Remote "Developer" Branch in Remote "Main" Branch mergen

== Erkenntnisse (Lessons learned)

=== Version Control System Workflow

Version Control Software unterstützt und ermöglicht unabhängige bis zu "chaotischen" Arbeitsweisen.
Dennoch ist habe wir festgestellt, dass es hilfreich sein kann eine Workflow zu defninieren, welcher zusätzlichen Arbeitsaufwand minimiert.

include::./version_control_system_workflow.adoc[]

<<<<<<< HEAD
=== Fortschritt visulaisieren

Im Gegensatz zu existierenden Objekten ist Software mit Sprache als Material eine Abstraktion.
Dem entsprechend schwierig ist die Visulaisierung des aktuellen Standes.
Hier muss sich noch eine System zur besseren Zusammenarbeit ausgedacht werden.
=======
=== Austausch über Fortschritt

Im Gegensatz zu existierenden Objekten ist das Material aus dem Software besteht Sprache.
Die zwei Hauptproblem die ein solches Material mit sich bringt sind Komplexität und Abstraktion.
Dem entsprechend schwierig ist die Visulaisierung des internen Standes des Projektes.
Es kann schwer sein nur durch das schauen auf ein Stück Quellcode zu erfassen, was der momentante Fortschritt ist.
Man sollte sich also innerhalb des Teams regelmäßig darüber austauschen, was der aktuelle Stand des Projektes ist und auf gute Dokumentation auch innerhalb des Codes achten.

=== Was ist gut?

Wenn man alleine ein Idee in einem Projekt umsetzt, fällt es oft einfach (bzw. es kommt natürlich) in welchem Maße man etwas implementiert.
Im Austausch mit anderen fällt jedoch oft auf, dass dies nicht der einzige Weg ist.
Nicht jeder hat die selbe Vorstellung von gut und jeder Mensch hat einen individuellen "Programmier Style".
Dies muss man sich bewusst werden.
>>>>>>> developer
