. Sicherstellen, dass der locale Branch, welcher mit dem Remote Branch "developer" verbunden ist, sich auf aktuellem Stand befindet.

.alternativ ``git switch``

[source,bash]
git checkout <local-developer-name>
git pull origin developer

.Erstelle dann eine neue Task, an der du arbeiten möchstest z.B.:

[source,bash]

git checkout -b task/<DeinName_Name deiner Task> //innerhalb der <> keine leerzeichen!

==== Änderungen committen

Jetzt arbeitest du in VSCode wie sonst auch. Wenn du fertig bist:


Um zu committen:

    . Source Control-Icon (Strg+Shift+G)
    . Geänderte Dateien werden gelistet. "+" bei den Dateien ab, die in den Commit sollen.
    . Oben im Eingabefeld eine Commit-Nachricht schreiben und commit


=== Task-Branch auf GitHub pushen

. gib im Terminal (immer von vsc!) folgendes ein:

[source,bash]

git push -u origin task/<DeinName_Name deiner Task>

=== Merge von deinem Task-branch auf developer
.Lokal mergen

[source,bash]

git checkout developer                  //wechselt auf die Ansicht von developer
git pull origin developer               //holt neueste developer-version von git
git merge --no-ff task/<DeinName_Name deiner Task> -m "Merge von task in developer"
git push origin developer               //pusht deine änderungen auf den developer-Branch in git

=== task-Branch löschen (optional)
[source, bash]

git push origin --delete task/<DeinName_Name deiner Task>       //löscht den remote-branch der Task auf git
git branch -d task/<DeinName_Name deiner Task>                  //löscht den lokalen Branch


== Für REVIEWER von developer-Code zusätzlich: Merge von developer → main

[source,bash]

git checkout main           //in main wechseln
git pull origin main        //main aktualisieren
git merge --no-ff developer -m "Merge developer into main"  //kein fast-foreward-merge, sondern immer neuer merge-commit
git push origin main         //lokaler merge in git pushen

== Kurzübersicht der Befehle

[cols="1,1",options="header"]
|===
|Aktion |Terminal-Befehl

|lokale branches auflisten (-a local & remote Branches)(-r remote-branches)
|git branch -a

|Repository klonen
|git clone <repo-url>

|Neuen Branch anlegen
|git checkout -b <name>

|Änderungen committen
|git add . && git commit -m "msg"

|Branch pushen
|git push -u origin <branch>

|Merge durchführen
|git merge --no-ff <branch>

|Branch löschen
|git branch -d <branch> + git push --delete origin <branch>
|===
